#!/bin/bash
curl https://releases.rancher.com/install-docker/19.03.sh | sh
usermod -aG docker ubuntu
apt-get install git -y
curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
cd /home/ubuntu
git clone https://github.com/MarceloMMacedo/devops.git
cd devops/exercicios/app
cd redis
docker build -t marcelomacedo/redis:devops .
docker run -d --name redis -p 6379:6379 marcelomacedo/redis:devops
docker ps
docker logs redis
cd ../node
docker build -t marcelomacedo/node:devops .
docker run -d --name node -p 8080:8080 --link redis marcelomacedo/node:devops
docker ps 
docker logs node
cd ../nginx
docker build -t marcelomacedo/nginx:devops .
docker run -d --name nginx -p 80:80 marcelomacedo/nginx:devops
docker ps
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls)
cd ..
docker-compose -f docker-compose.yml up -d
curl <ip>:80 

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.3 --server https://rancher.ualphb.online --token s6tgwm8wvqvkgwn7ljcz7s4xbcqh8zfl8tq89xlrk5bzfbcfzblj2c --ca-checksum f218662cb83a526ec83e4b7c27abb67453c7f1822234a3f7550012a967f396c2 --etcd --controlplane --worker


